os: linux
language: python
python: "2.7"

git:
  depth: false

# Install ansible
addons:
  apt:
    update: true
    packages:
      - python-pip

services:
  - docker

before_install:
  - sudo docker pull docker.io/tripleomaster/centos-binary-collectd:current-tripleo-rdo

install:
  # Install ansible
  - pip install ansible ansible-lint

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-lint
  # Run the role
  - ansible-playbook tests/test.yml -i tests/inventory --extra-vars "collectd_conf_output_dir=$HOME/collectd.conf.d" && cat $HOME/collectd.conf.d/*
  - sudo docker run -dti --name collectd-test --net=host -v $HOME/collectd.conf.d:/opt/collectd/etc/collectd.conf.d -v /var/run:/var/run -v /tmp:/tmp -v `pwd`/tests/kolla_config_files/:/var/lib/kolla/config_files/ -e KOLLA_CONFIG_STRATEGY=COPY_ALWAYS --privileged tripleomaster/centos-binary-collectd:current-tripleo-rdo
  - sudo docker logs collectd-test
  - sudo docker exec collectd-test collectdctl -s /var/run/collectd-socket listval

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
