---
- debug:
    var: collectd_plugins

- block:
  - name: "Remove files from {{ collectd_conf_output_dir }}"
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "{{ collectd_conf_output_dir }}/"
      - "{{ collectd_conf_output_dir }}/../collectd.conf"

  - name: "Create config dir at {{ collectd_conf_output_dir }}"
    file:
      path: "{{ collectd_conf_output_dir }}/"
      state: directory
      mode: 0644

  - name: "Create core collectd config beside {{ collectd_conf_output_dir }}"
    template:
      src: collectd.conf.j2
      dest: "{{ collectd_conf_output_dir }}/../collectd.conf"
      mode: 0644

  - name: "Create plugin config files in {{ collectd_conf_output_dir }}"
    template:
      src: "{{ item }}.conf.j2"
      dest: "{{ collectd_conf_output_dir }}/{{ item }}.conf"
      mode: 0644
    loop: "{{ collectd_plugins }}"
  when: templates_generate_to_disk

- block:
  - name: "Create core collectd config"
    set_fact: "{{ item }}={{ lookup('template', item + '.conf.j2') }}"
    loop: "{{ collectd_plugins }}"

  - debug:
      var: "{{ item }}"
    loop: "{{ collectd_plugins }}"
  when: not templates_generate_to_disk
