---
dependency:
  name: galaxy
  options:
    role-file: molecule/common/requirements.yml
driver:
  name: ${CONTAINER_BIN:-podman}

platforms:
  - name: collectd-test
    image: quay.io/tripleomaster/openstack-collectd:current-tripleo
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible

scenario:
  name: extra_typesdb
  test_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy
    - cleanup
