---
- hosts:
    - collectd-test
    - collectd-server
  become: true
  tasks:
    - when: "{{ lookup('env', 'CONTAINER_BIN') | default('podman', True) == 'podman' }}"
      block:
        - name: "Get IP address of collectd-server"
          local_action: shell podman inspect --format \{\{.NetworkSettings.IPAddress\}\} collectd-server
          register: output
        - name: "Set the server_ip"
          set_fact:
            server_ip: "{{ output.stdout }}"
        - debug:
            var: server_ip

- name: Converge client
  hosts: collectd-test
  roles:
    - role: "{{ playbook_dir }}/../../../collectd-config-ansible-role"
  vars:
        collectd_conf_output_dir: "/etc/collectd.d"
        collectd_plugin_network_server:
          - name: "{{ server_ip | default('192.168.42.2') }}"
        collectd_plugin_network_reportstats: true
        collectd_plugins:
          - cpu
          - df
          - logfile
          - memory
          - network
          - unixsock

- name: Converge server
  hosts: collectd-server
  roles:
    - role: "{{ playbook_dir }}/../../../collectd-config-ansible-role"
  vars:
        collectd_conf_output_dir: "/etc/collectd.d"
        collectd_plugin_network_listen:
          - address: "{{ server_ip | default('192.168.42.2') }}"
        collectd_plugins:
          - logfile
          - network
          - unixsock
