---
- name: Converge client
  hosts: collectd-test
  roles:
    - role: "{{ playbook_dir }}/../../../collectd-config-ansible-role"
  vars:
        collectd_conf_output_dir: "/etc/collectd.d"
        collectd_plugin_network_server:
          - name: "192.168.42.2"
        collectd_plugin_network_reportstats: true
        collectd_plugins:
          - cpu
          - df
          - logfile
          - memory
          - network
          - unixsock

- name: Converge server
  hosts: collectd-server
  roles:
    - role: "{{ playbook_dir }}/../../../collectd-config-ansible-role"
  vars:
        collectd_conf_output_dir: "/etc/collectd.d"
        collectd_plugin_network_listen:
          - address: "192.168.42.2"
        collectd_plugins:
          - logfile
          - network
          - unixsock
