---
- name: Converge
  hosts: collectd-test
  roles:
    - role: "{{ playbook_dir }}/../../../collectd-config-ansible-role"
  vars:
        collectd_plugin_logfile_loglevel: "debug"
        collectd_conf_output_dir: "/etc/collectd.d"
        collectd_plugin_network_server:
          - name: "192.168.42.2"
            #securitylevel: None
            #username: "first_user"
            #password: "firstpass"
        collectd_plugins:
          - cpu
          - df
          - logfile
          - memory
          - network
          - unixsock

- name: Converge
  hosts: collectd-server
  roles:
    - role: "{{ playbook_dir }}/../../../collectd-config-ansible-role"
  vars:
        collectd_conf_output_dir: "/etc/collectd.d"
        collectd_plugin_network_listen:
          - address: "192.168.42.2"
            # securitylevel: "blah"
            # authfile "somefile"
        collectd_plugins:
          - logfile
          - network
          - unixsock
