---
dependency:
  name: galaxy
  options:
    role-file: molecule/common/requirements.yml
driver:
  name: docker
platforms:
  - name: collectd-test
    image: quay.io/tripleomaster/openstack-collectd:current-tripleo
    docker_networks:
      - name: foo
        ipam_config:
          - subnet: "192.168.42.0/24"
            gateway: "192.168.42.254"
    networks:
      - name: foo
        ipv4_address: "192.168.42.1"
  - name: collectd-server
    image: quay.io/tripleomaster/openstack-collectd:current-tripleo
    privileged: true
    networks:
      - name: foo
        ipv4_address: "192.168.42.2"

provisioner:
  name: ansible
  log: true
verifier:
  name: ansible

scenario:
  name: test_network
  test_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy
    - cleanup
