---
- name: Prepare
  hosts: all
  tasks:
    - name: "Set up OpsTools repo to get collectd-* packages"
      yum_repository:
        name: centos-opstools-release
        description: CentOS OpsTools
        baseurl: http://mirror.centos.org/centos/8/opstools/x86_64/collectd-5
        gpgcheck: no
