---
- name: Converge
  hosts: all
  roles:
    - role: "{{ playbook_dir }}/../../../collectd-config-ansible-role"
  vars:
        collectd_conf_output_dir: "/etc/collectd.d"
        collectd_plugins:
          # There are some undefined vars in the template that are causing
          # rendering to fail, these will be updated
          - amqp1
          # collectd image doesn't have capabilities plugin
          # - capabilities
          - ceph
          - connectivity
          - contextswitch
          - cpu
          - cpufreq
          - cpusleep
          - csv
          # collectd image doesn't have dcpmm plugin
          # - dcpmm
          - df
          - disk
          - dns
          - ethstat
          - exec
          - hddtemp
          - hugepages
          - intel_pmu
          - intel_rdt
          - interface
          - ipc
          # The rendered conf file is not syntactically correct yet
          # - ipmi
          - irq
          - load
          - logfile
          - mcelog
          # collectd image doesn't have mdevents plugin
          # - mdevents
          - memory
          - netlink
          - network
          - ntpd
          - numa
          - ovs_stats
          - ping
          - processes
          - procevent
          - smart
          - syslog
          - swap
          - unixsock
          - uptime
          - uuid
          - virt
          - vmem
          - write_http
