---
dependency:
  name: galaxy
  options:
    role-file: molecule/common/requirements.yml
driver:
  name: docker
platforms:
  - name: collectd-test
    image: quay.io/tripleomaster/openstack-collectd:current-tripleo
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
lint: |
  ansible-lint **/*.yml

scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy
    - cleanup
