---
dependency:
  name: galaxy
  options:
    role-file: molecule/common/requirements.yml
driver:
  name: docker
platforms:
  - name: collectd-test
    image: docker.io/tripleomaster/centos-binary-collectd:current-tripleo-rdo
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
lint: |
  yamllint .
  ansible-lint .

scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    # - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - destroy
    - cleanup
