---
- name: Verify
  hosts: collectd-test
  tasks:
    - name: Check for files in conf output dir
      find:
        paths: /etc/collectd.d
        patterns: '*.conf'
      register: output
      failed_when: output.files|length == 0

    - name: "Check for collectd.conf"
      find:
        paths: /etc/
        patterns: collectd.conf
      register: conf
      failed_when: conf.files|length != 1
    - debug:
        var: conf.files | length

    - name: "start collectd"
      command:
        /usr/sbin/collectd -C /etc/collectd.conf

- hosts: localhost
  tasks:
    - name: "Run the collectd test from STF functional-tests"
      include_role:
        name: functional_tests
        tasks_from: test_collectd
      vars:
        collectd_container_name: 'collectd-test'
