---
- name: Verify
  hosts: collectd-test
  tasks:
    - name: Check for files in conf output dir
      find:
        paths: /etc/collectd.d
        patterns: '*.conf'
      register: output
      failed_when: output.files|length == 0

    - name: "Check for collectd.conf"
      find:
        paths: /etc/
        patterns: collectd.conf
      register: conf
      failed_when: conf.files|length != 1
    - debug:
        var: conf.files | length

    - name: "(Re)start collectd"
      block:
        - name: "Kill running collectd process"
          command:
            pkill -e -c collectd
          ignore_errors: true

        - name: "Start collectd"
          command:
            /usr/sbin/collectd -C /etc/collectd.conf

    - name: "Check for metrics from different plugins"
      shell: |
        set -o pipefail
        collectdctl -s /var/run/collectd-socket listval | grep hugepages

- hosts: localhost
  tasks:
    - name: "Run the collectd test from STF functional-tests"
      include_role:
        name: functional_tests
        tasks_from: test_collectd
      vars:
        collectd_container_name: 'collectd-test'
