name: CI

on: push

jobs:
  molecule:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
          - extra_typesdb
          - non_default_options
          - test_exec
          - test_network
          - test_python
    env:
      PY_COLORS: '1'
      ANSIBLE_FORCE_COLOR: '1'
      CONTAINER_BIN: docker

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Pre-pull container
        run: |
          sudo docker pull quay.io/tripleomaster/openstack-collectd:current-tripleo
      - name: "Molecule"
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }}
          molecule_working_dir: ${{ github.repository }}

  lint:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    env:
      CONTAINER_BIN: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Pre-pull container
        run: |
          sudo docker pull quay.io/tripleomaster/openstack-collectd:current-tripleo
      - name: "Molecule"
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: lint
          molecule_working_dir: ${{ github.repository }}
